apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 109
        supplementalGroups:
          - 44
          - 109
      nodeSelector:
        kubernetes.io/hostname: nexus
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          securityContext:
            privileged: true
          env:
            - name: LIBVA_DRIVER_NAME
              value: iHD
            - name: LIBVA_DRIVERS_PATH
              value: /usr/lib/x86_64-linux-gnu/dri
            - name: VAAPI_DEVICE
              value: /dev/dri/renderD128
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: dev-dri
              mountPath: /dev/dri
              readOnly: true
            - name: va-drivers
              mountPath: /usr/lib/x86_64-linux-gnu/dri
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: media
          persistentVolumeClaim:
            claimName: media-storage
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: va-drivers
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/dri
            type: Directory
